### ISSUE TITLE
1.15 issues

### ISSUE THREAD

**Issue by Darkere** [drizzs/FoamDome#1]
When inserting cartridge it goes into offhand on the first click
Tooltips need the proper color

foamdome-1.0 
forge 30.0.15

**Comment by drizzs** [comment]
Yeah that inserting cartridge into the offhand stuff isn't something i can just fix(i released it knowing this was happening). There is nothing in my code that uses the offhand, or adds items to the offhand or even sees the offhand as a usable hand at all! I have been looking into why this is happening. Hopefully i'll figure it out. I just can't say for sure at this point this isn't an issue with how forge interacts with how i handle inserting and extracting items. Either way i'll take a deeper look to find out why this is happening (it was pretty annoying but it worked so i was like could be worse)

I need to add text formatting to the tooltips! I will more than likely do that over this week! 

Thanks Darkere! I really appreciate people posting on the github about this stuff!

**Comment by drizzs** [comment]
my 1.14.4 code is identical so it doesn't make sense why it happens on 1.15 but not 1.14

**Comment by drizzs** [comment]
Took a while but its fixed in new update!
